name: CI/CD
on:
  push:
    branches: [ master ]

jobs:
  test_suite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
      - name: Set Up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run Tests
        run: |
          python -m unittest discover tests/
  deployment:
    needs: test_suite
    runs-on: ubuntu-latest
    steps:
      - name: Fresh clone & repo install
        uses: appleboy/ssh-action@master
        with:
          host: 3.229.170.248
          username: github-actions
          key: ${{ secrets.SSHKEY }}
          port: 22
          script: |
            rm -rf Surf-report
            git clone https://github.com/Karen-Stewart80/Surf-report.git
            python3.8 -m venv /home/github-actions/Surf-report/venv
            source /home/github-actions/Surf-report/venv/bin/activate
            pip install -r /home/github-actions/Surf-report/requirements.txt